.Dd June 1, 2020
.Dt SELECTION 1
.Os
.Sh NAME
.Nm selection
.Nd find arbitrage triangles in order books
.Sh SYNOPSIS
.Nm
.Ar idir
.Ar odir
.Op Fl r
.Op Fl t Ar num
.Sh DESCRIPTION
.Nm
finds positive arbitrage opportunities in the order books stored in
.Ar idir ,
presumably downloaded with
.Xr getbook 1
and cleaned with
.Xr cleanup 1 .
The input data are expected to consist of csv lines containing
.Ar id ,
.Ar bid ,
.Ar ask
and
.Ar timestamp ,
where
.Ar bid
and
.Ar ask
are 2D arrays containing price and amount.
The positive triangles are then reported in files stored in
.Ar odir .
.Pp
With the
.Fl r
option,
.Nm
will process
.Ar idir
recursively.
If the
.Fl t
option is also given,
.Nm
will distribute the recursive work on subdirectories into
.Ar num
threads.
.Sh SEE ALSO
.Xr cleanup 1 ,
.Xr getbook 1
.Sh AUTHORS
.An Čeněk Žid
