.Dd June 1, 2020
.Dt Selection 1
.Os
.Sh NAME
.Nm selection
.Nd find arbitrage triangles in order books
.Sh SYNOPSIS
.Nm
.Ar input_dir output_dir [<options>]
.Sh DESCRIPTION
.Nm
finds the positive arbitrage opportunities in the given order book data. The input data are supposed to be in the following .csv format
.Ar id bid ask timestamp
Where
.Ar bid ask
are 2-D arrays (the first column is price and the second column is amount).
\n
.Sh OPTIONS
.SH OPTIONS
.TP
\-r Add if you want the program to go through the children directories instead of the given directory.
\n
\-t,
.Ar -t NUMBER
Set the number of threads. This option is only relevant if \-r flag is also written.
The program then redistributes the child directories to the number of given threads (one thread in default).
.Sh AUTHORS
.An Čeněk Žid
