.Dd May 18, 2020
.Dt GETBOOK 1
.Os
.Sh NAME
.Nm getbook
.Nd download order books of Binance
.Sh SYNOPSIS
python3 getbook.py
.Ar output_directory
.Sh DESCRIPTION
.Nm
downloads the order books from Binance for every currency pair written in the ./relevant_symbols file and then saves
them into the given directory entered as a parameter. The order books are saved into separate .csv files
distinguished by the currency pair and current date (new file is created every day for every currency pair).
.Sh AUTHORS
.An Čeněk Žid
