.Dd June 1, 2020
.Dt GETBOOK 1
.Os
.Sh NAME
.Nm getbook
.Nd download order books from Binance
.Sh SYNOPSIS
python3 getbook.py
.Ar directory
.Sh DESCRIPTION
.Nm
downloads the order books from Binance for every currency pair mentioned in
.Pa ./relevant_symbols
and saves them into the given
.Ar directory .
The order books are stored in separate .csv files
named according to the currency pair and current date
(typically, a new file is created every day for every currency pair).
.Pp
To connect to Binance,
a valid
.Pa apikey.txt
and
.Pa privatekey.txt
file needs to be present in the executing directory.
.Sh AUTHORS
.An Čeněk Žid
