.Dd June 1, 2020
.Dt CLEANUP 1
.Os
.Sh NAME
.Nm cleanup
.Nd clean up csv orderbooks
.Sh SYNOPSIS
python3 cleanup.py
.Ar idir
.Ar odir
.Op Fl r
.Sh DESCRIPTION
.Nm
goes through the lines of csv order books downloaded by
.Xr getbook 1
into
.Ar idir
(recursively, if the
.Fl r
option is given).
Every line is checked for correct datatypes and a correct timestamp;
ID order monotonicity is ensured and ID dupplicities are removed
(the occurence with the lowest timestamp is kept).
.Nm
will remove any line that does not have an integer ID,
does not have a float timestamp,
or has any of the expected columns missing.
The lines are then sorted according to their ID and timestamp
and saved into identically named files in
.Pa odir .
.Sh SEE ALSO
.Xr getbook 1
.Sh AUTHORS
.An Čeněk Žid
